using System;
Console.WriteLine("--- BANCO SENAI: GESTÃO DE COMPRAS E SALDO ---");
Console.Write("Nome do Cliente: ");
string nomeCliente = Console.ReadLine();
Console.Write("Saldo Atual em Conta (R$): ");
decimal saldoAtual = Convert.ToDecimal(Console.ReadLine());
Console.WriteLine("\n--- REGISTRO DE COMPRAS ---");
Console.Write("Descrição da Compra 1: ");
string desc1 = Console.ReadLine();
Console.Write("Valor da Compra 1 (R$): ");
decimal valor1 = Convert.ToDecimal(Console.ReadLine());
Console.Write("Descrição da Compra 2: ");
string desc2 = Console.ReadLine();
Console.Write("Valor da Compra 2 (R$): ");
decimal valor2 = Convert.ToDecimal(Console.ReadLine());
Console.Write("Descrição da Compra 3: ");
string desc3 = Console.ReadLine();
Console.Write("Valor da Compra 3 (R$): ");
decimal valor3 = Convert.ToDecimal(Console.ReadLine());
decimal totalGastos = valor1 + valor2 +  - 20;
decimal patrimonioDisponivel = saldoAtual - totalGastos;
Console.WriteLine("\n--- RESUMO FINANCEIRO FINAL ---");
Console.WriteLine($"CLIENTE: {nomeCliente.ToUpper()}");
Console.WriteLine($"SALDO INICIAL: R$ {saldoAtual}");
Console.WriteLine($"TOTAL DE GASTOS: R$ {totalGastos}");
Console.WriteLine($"PATRIMÔNIO DISPONÍVEL PARA SAQUE: R$ {patrimonioDisponivel}");
Console.WriteLine("-------------------------------------------");
